# Generated by Django 5.1.3 on 2025-03-09 16:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminid', models.CharField(max_length=50, unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custid', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobileno', models.CharField(max_length=15)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerid', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('deptname', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeddesc', models.TextField()),
                ('feedrate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feeddate', models.DateTimeField(auto_now_add=True)),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replymessage', models.TextField()),
                ('replydate', models.DateTimeField(auto_now_add=True)),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.customer')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.feedback')),
                ('managerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.manager')),
            ],
        ),
    ]
